In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("done.csv")

In [3]:
check = pd.Series(data["Аниме"])
check.loc[check.values==True]=1
check.loc[check.values==False]=0
check.astype('int8')

0      1
1      0
2      0
3      1
4      1
      ..
193    0
194    1
195    1
196    0
197    0
Name: Аниме, Length: 198, dtype: int8

In [4]:
data.drop(["Unnamed: 0", "time", "Драма", "Боевик", "Аниме", "Комедия", "Фантастика", "Исторический фильм", "Детектив", "Трагедия", "Фильм ужасов"], axis=1, inplace=True)

In [5]:
data.head()

,sex,vegan,rest,games,series,books,english,USSR_lover,child_offence_Не били,child_offence_Разве что по делу,...,subject_История,subject_Литература,subject_Матеша,subject_Физика,subject_Химия,crimea_Мне всё равно,crimea_Отрицательно,crimea_Положительно,putin_good,rebel
0,1,2,1,1,1,3,1,0,1,0,...,0,1,0,0,0,0,0,1,0,1
1,0,2,1,3,1,2,3,0,0,1,...,0,0,1,0,0,1,0,0,0,1
2,1,2,0,0,1,3,3,0,0,1,...,0,0,0,0,0,1,0,0,1,0
3,0,0,0,2,3,4,3,1,0,1,...,0,0,0,0,0,0,1,0,1,0
4,0,1,1,6,4,3,1,1,1,0,...,0,0,0,0,0,1,0,0,1,0

In [15]:
from sklearn.model_selection import train_test_split
from catboost import CatBoostClassifier, Pool

In [16]:
X_train, X_validation, Y_train, Y_validation = train_test_split(data, check, train_size=0.5, random_state=1234)

In [17]:
X_validation.head()

,sex,vegan,rest,games,series,books,english,USSR_lover,child_offence_Не били,child_offence_Разве что по делу,...,subject_История,subject_Литература,subject_Матеша,subject_Физика,subject_Химия,crimea_Мне всё равно,crimea_Отрицательно,crimea_Положительно,putin_good,rebel
195,0,2,0,1,4,4,0,1,0,0,...,0,0,1,0,0,1,0,0,0,1
155,1,1,1,0,4,5,1,1,0,1,...,0,1,0,0,0,1,0,0,1,0
31,1,4,1,0,3,6,1,1,1,0,...,0,1,0,0,0,1,0,0,1,0
48,1,2,1,0,5,3,4,0,0,1,...,0,0,0,0,0,0,0,1,1,0
63,1,2,1,0,2,2,3,0,1,0,...,0,0,0,0,0,0,0,1,1,0

In [18]:
X_train.head()

,sex,vegan,rest,games,series,books,english,USSR_lover,child_offence_Не били,child_offence_Разве что по делу,...,subject_История,subject_Литература,subject_Матеша,subject_Физика,subject_Химия,crimea_Мне всё равно,crimea_Отрицательно,crimea_Положительно,putin_good,rebel
12,1,0,0,0,0,2,1,0,1,0,...,0,0,1,0,0,0,0,1,1,0
188,0,1,1,3,2,4,1,1,0,1,...,0,1,0,0,0,1,0,0,1,0
167,1,3,1,1,4,3,0,1,1,0,...,0,0,0,0,1,0,1,0,1,0
161,0,0,0,1,4,3,2,0,1,0,...,0,0,0,0,0,1,0,0,0,1
1,0,2,1,3,1,2,3,0,0,1,...,0,0,1,0,0,1,0,0,0,1

In [22]:
import numpy as np

In [28]:
best_model = CatBoostClassifier(iterations=10)

In [30]:
train_data= Pool(data=X_train, label=Y_train, weight=np.ones(Y_train.size))

TypeError: No matching signature found